// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#SQYQPOOOeQPO'#C_OjQQO'#CaO{QPO'#CpOOQO'#Cj'#CjQYQPOOOOQO,58y,58yOOQO'#Cf'#CfOOQO'#Cc'#CcOOQO'#Ck'#CkO!QQQO,58{OOQO'#Cl'#ClO!XQPO,59[OOQO-E6h-E6hOOQO-E6i-E6iOOQO-E6j-E6j",
  stateData: "!s~OcOSPOS~OSROUQOePO~OSUO~OWWOXWOZVO[VO]WO~OfZO~OfTa~PjOfZOSdaUdaadaeda~OUWXS]Z[S~",
  goto: "!YePPPfPfPjPPnPPPrx!OPPP!UTROTTXQYTWQYQTOR]TQYQR^YQ[RR_[TSOT",
  nodeNames: "⚠ Comment Program Track Label Instruction Opcode Operand Instrument Register Value Immediate Memory Identifier",
  maxTerm: 22,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "9R~RjXY!sYZ#R]^!spq!s}!O#W!Q![#^!]!^#f!c!d$W!d!e&^!e!f%P!f!g(]!g!l%P!l!m*X!m!n%P!n!o+p!o!r%P!r!s,m!s!t%P!t!u.R!u!v0`!v!w3}!w!x%P!x!y6_!y!}%P!}#O7_#T#o%P~!xRc~XY!s]^!spq!s~#WOf~~#ZP!Q![#^~#cPZ~!Q![#^~#iTOY#fYZ#xZ;'S#f;'S;=`$Q<%lO#f~#}PP~YZ#x~$TP;=`<%l#f~$]U]Q!Q![$o![!]$z!c!f%P!f!g%b!g!}%P#T#o%P~$tQ]Q!Q![$o![!]$z~%POS~~%US]Q!Q![$o![!]$z!c!}%P#T#o%P~%gU]Q!Q![$o![!]$z!c!f%P!f!g%y!g!}%P#T#o%P~&QSU~]Q!Q![$o![!]$z!c!}%P#T#o%P~&cW]Q!Q![$o![!]$z!c!r%P!r!s&{!s!t%P!t!u'w!u!}%P#T#o%P~'QU]Q!Q![$o![!]$z!c!o%P!o!p'd!p!}%P#T#o%P~'kSX~]Q!Q![$o![!]$z!c!}%P#T#o%P~'|T]Q!Q![$o![!]$z!c!|%P!|!}%y#T#o%P~(bU]Q!Q![$o![!]$z!c!t%P!t!u(t!u!}%P#T#o%P~(yU]Q!Q![$o![!]$z!c!w%P!w!x)]!x!}%P#T#o%P~)bU]Q!Q![$o![!]$z!c!o%P!o!p)t!p!}%P#T#o%P~){SW~]Q!Q![$o![!]$z!c!}%P#T#o%P~*^U]Q!Q![$o![!]$z!c!w%P!w!x*p!x!}%P#T#o%P~*uU]Q!Q![$o![!]$z!c!o%P!o!p+X!p!}%P#T#o%P~+^U]Q!Q![$o![!]$z!c!r%P!r!s%y!s!}%P#T#o%P~+uU]Q!Q![$o![!]$z!c!q%P!q!r,X!r!}%P#T#o%P~,^T]Q!Q![$o![!]$z!c!d%b!d!}%P#T#o%P~,rU]Q!Q![$o![!]$z!c!n%P!n!o-U!o!}%P#T#o%P~-ZT]Q!Q![$o![!]$z!c!d-j!d!}%P#T#o%P~-oU]Q!Q![$o![!]$z!c!{%P!{!|%y!|!}%P#T#o%P~.WU]Q!Q![$o![!]$z!c!g%P!g!h.j!h!}%P#T#o%P~.oW]Q!Q![$o![!]$z!c!i%P!i!j/X!j!u%P!u!v/w!v!}%P#T#o%P~/^S]Q!Q![/j![!]$z!c!}%P#T#o%P~/qQX~]Q!Q![/j![!]$z~/|U]Q!Q![$o![!]$z!c!v%P!v!w%y!w!}%P#T#o%P~0eW]Q!Q![$o![!]$z!c!v%P!v!w0}!w!{%P!{!|2f!|!}%P#T#o%P~1SU]Q!Q![$o![!]$z!c!q%P!q!r1f!r!}%P#T#o%P~1kU]Q!Q![$o![!]$z!c!t%P!t!u1}!u!}%P#T#o%P~2SU]Q!Q![$o![!]$z!c!g%P!g!h%y!h!}%P#T#o%P~2kU]Q!Q![$o![!]$z!c!p%P!p!q2}!q!}%P#T#o%P~3SU]Q!Q![$o![!]$z!c!v%P!v!w3f!w!}%P#T#o%P~3kU]Q!Q![$o![!]$z!c!j%P!j!k)t!k!}%P#T#o%P~4SU]Q!Q![$o![!]$z!c!t%P!t!u4f!u!}%P#T#o%P~4kT]Q!Q![$o![!]$z!c!d4z!d!}%P#T#o%P~5PU]Q!Q![$o![!]$z!c!e%P!e!f5c!f!}%P#T#o%P~5hU]Q!Q![$o![!]$z!c!m%P!m!n5z!n!}%P#T#o%P~6RSeP]Q!Q![$o![!]$z!c!}%P#T#o%P~6dU]Q!Q![$o![!]$z!c!q%P!q!r6v!r!}%P#T#o%P~6{U]Q!Q![$o![!]$z!c!n%P!n!o'd!o!}%P#T#o%P~7bT}!O7q!Q![7w!d!e8V!t!u8i!x!y8u~7tP!Q![7w~7zQ!Q![7w#P#Q8Q~8VO[~~8YP!r!s8]~8`P!o!p8c~8fP#P#Q8Q~8lP!g!h8o~8rP!i!j7q~8xP!q!r8{~9OP!n!o8c",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 72
})
