// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Label = 3,
  Instruction = 4,
  Opcode = 5,
  Operand = 6,
  Instrument = 7,
  Register = 8,
  Immediate = 9,
  Memory = 10,
  LabelRef = 11
