// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Track = 3,
  Label = 4,
  Instruction = 5,
  Opcode = 6,
  Operand = 7,
  Instrument = 8,
  Register = 9,
  Immediate = 10,
  Memory = 11,
  LabelRef = 12
